name = "trade-vision"
main = ".open-next/worker.js"
compatibility_date = "2026-05-28"
compatibility_flags = ["nodejs_compat_v2"]

workers_dev = false

[[routes]]
pattern = "trade-vision.io/*"
zone_id = "bb8b0eb180e5759d9a81f51e44e6bc6d"

[[routes]]
pattern = "www.trade-vision.io/*"
zone_id = "bb8b0eb180e5759d9a81f51e44e6bc6d"

[vars]
NODE_ENV = "production"
